package io.github.muindor.tcresearchsolver.solver

// Aspect data for the Thaumcraft research minigame, extracted directly from the
// GregTech: New Horizons modpack jars (Thaumcraft 4.2.3.5a + addons).
// Transcribed from reference/ts-solver/data/raw.ts in declaration order. Do not reorder.

val PRIMALS: List<String> = listOf("air", "earth", "fire", "water", "order", "entropy")

// compound -> Pair(component1, component2)  (base Thaumcraft graph)
// MUST use linkedMapOf to preserve declaration/insertion order (gotcha G2).
val COMBINATIONS_4_2_2_0: LinkedHashMap<String, Pair<String, String>> = linkedMapOf(
    "void" to Pair("air", "entropy"),
    "light" to Pair("air", "fire"),
    "weather" to Pair("air", "water"),
    "motion" to Pair("air", "order"),
    "cold" to Pair("fire", "entropy"),
    "crystal" to Pair("earth", "order"),
    "life" to Pair("water", "earth"),
    "poison" to Pair("water", "entropy"),
    "energy" to Pair("order", "fire"),
    "exchange" to Pair("entropy", "order"),
    "metal" to Pair("earth", "crystal"),
    "death" to Pair("life", "entropy"),
    "flight" to Pair("air", "motion"),
    "darkness" to Pair("void", "light"),
    "soul" to Pair("life", "death"),
    "heal" to Pair("life", "order"),
    "travel" to Pair("motion", "earth"),
    "eldritch" to Pair("void", "darkness"),
    "magic" to Pair("void", "energy"),
    "aura" to Pair("magic", "air"),
    "taint" to Pair("magic", "entropy"),
    "slime" to Pair("life", "water"),
    "plant" to Pair("life", "earth"),
    "tree" to Pair("air", "plant"),
    "beast" to Pair("motion", "life"),
    "flesh" to Pair("death", "beast"),
    "undead" to Pair("motion", "death"),
    "mind" to Pair("fire", "soul"),
    "senses" to Pair("air", "soul"),
    "man" to Pair("beast", "mind"),
    "crop" to Pair("plant", "man"),
    "mine" to Pair("man", "earth"),
    "tool" to Pair("man", "order"),
    "harvest" to Pair("crop", "tool"),
    "weapon" to Pair("tool", "fire"),
    "armor" to Pair("tool", "earth"),
    "hunger" to Pair("life", "void"),
    "greed" to Pair("man", "hunger"),
    "craft" to Pair("man", "tool"),
    "cloth" to Pair("tool", "beast"),
    "mechanism" to Pair("motion", "tool"),
    "trap" to Pair("motion", "entropy"),
)

data class Addon(
    val name: String,
    val aspects: List<String>,
    val combinations: LinkedHashMap<String, Pair<String, String>>,
)

val ADDONS: Map<String, Addon> = linkedMapOf(
    "fm" to Addon(
        name = "Forbidden Magic",
        aspects = listOf("lust", "nether", "pride", "gluttony", "envy", "sloth", "wrath"),
        combinations = linkedMapOf(
            "lust" to Pair("flesh", "hunger"),
            "nether" to Pair("fire", "magic"),
            "pride" to Pair("flight", "void"),
            "gluttony" to Pair("hunger", "void"),
            "envy" to Pair("senses", "hunger"),
            "sloth" to Pair("trap", "soul"),
            "wrath" to Pair("weapon", "fire"),
        ),
    ),
    "mb" to Addon(
        name = "Magic Bees",
        aspects = listOf("time"),
        combinations = linkedMapOf(
            "time" to Pair("void", "order"),
        ),
    ),
    "gt" to Addon(
        name = "Gregtech",
        aspects = listOf("stupidity", "cheatiness", "electricity", "magnetism", "radioactivity", "aequalitas", "vesania", "primordium", "astrum", "gloria"),
        combinations = linkedMapOf(
            "stupidity" to Pair("mind", "entropy"),
            "cheatiness" to Pair("mine", "greed"),
            "electricity" to Pair("energy", "mechanism"),
            "magnetism" to Pair("metal", "travel"),
            "radioactivity" to Pair("light", "energy"),
            "aequalitas" to Pair("mind", "order"),
            "vesania" to Pair("mind", "taint"),
            "primordium" to Pair("void", "motion"),
            "astrum" to Pair("light", "primordium"),
            "gloria" to Pair("man", "travel"),
        ),
    ),
    "tb" to Addon(
        name = "Thaumic Boots",
        aspects = listOf("caelum", "tabernus"),
        combinations = linkedMapOf(
            "caelum" to Pair("crystal", "metal"),
            "tabernus" to Pair("armor", "travel"),
        ),
    ),
    "av" to Addon(
        name = "Avaritia",
        aspects = listOf("terminus"),
        combinations = linkedMapOf(
            "terminus" to Pair("greed", "eldritch"),
        ),
    ),
)

// english/latin key -> latin icon basename (aspects/color/<basename>.png)
val TRANSLATE: Map<String, String> = linkedMapOf(
    "air" to "aer",
    "earth" to "terra",
    "fire" to "ignis",
    "water" to "aqua",
    "order" to "ordo",
    "entropy" to "perditio",
    "void" to "vacuos",
    "light" to "lux",
    "weather" to "tempestas",
    "motion" to "motus",
    "cold" to "gelum",
    "crystal" to "vitreus",
    "life" to "victus",
    "poison" to "venenum",
    "energy" to "potentia",
    "exchange" to "permutatio",
    "metal" to "metallum",
    "death" to "mortuus",
    "flight" to "volatus",
    "darkness" to "tenebrae",
    "soul" to "spiritus",
    "heal" to "sano",
    "travel" to "iter",
    "eldritch" to "alienis",
    "magic" to "praecantatio",
    "aura" to "auram",
    "taint" to "vitium",
    "slime" to "limus",
    "plant" to "herba",
    "tree" to "arbor",
    "beast" to "bestia",
    "flesh" to "corpus",
    "undead" to "exanimis",
    "mind" to "cognitio",
    "senses" to "sensus",
    "man" to "humanus",
    "crop" to "messis",
    "mine" to "perfodio",
    "tool" to "instrumentum",
    "harvest" to "meto",
    "weapon" to "telum",
    "armor" to "tutamen",
    "hunger" to "fames",
    "greed" to "lucrum",
    "craft" to "fabrico",
    "cloth" to "pannus",
    "mechanism" to "machina",
    "trap" to "vinculum",
    "terminus" to "terminus",
    "lust" to "luxuria",
    "nether" to "infernus",
    "pride" to "superbia",
    "gluttony" to "gula",
    "envy" to "invidia",
    "sloth" to "desidia",
    "wrath" to "ira",
    "stupidity" to "strontio",
    "cheatiness" to "nebrisum",
    "electricity" to "electrum",
    "magnetism" to "magneto",
    "radioactivity" to "radio",
    "aequalitas" to "aequalitas",
    "vesania" to "vesania",
    "primordium" to "primordium",
    "astrum" to "astrum",
    "gloria" to "gloria",
    "time" to "tempus",
    "caelum" to "caelum",
    "tabernus" to "tabernus",
)
